Traceback (most recent call last):
  File "D:\Digit_recognizer_AI_stuff\LLM_Python_Folder\import_data.py", line 3, in <module>
    print('Model accuracy after each epoch:', model.eval())
                                              ^^^^^
NameError: name 'model' is not defined
